CREATE TABLE IF NOT EXISTS product_sourcing_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NULL,
    session_key VARCHAR(190) NULL,
    customer_name VARCHAR(190) NULL,
    customer_email VARCHAR(190) NULL,
    customer_phone VARCHAR(80) NULL,
    source VARCHAR(40) NOT NULL DEFAULT 'ai',
    existing_product_id BIGINT UNSIGNED NULL,
    requested_brand VARCHAR(120) NULL,
    requested_model VARCHAR(190) NOT NULL,
    requested_variant VARCHAR(190) NULL,
    preferences_json LONGTEXT NULL,
    ai_result_json LONGTEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'new',
    admin_notes TEXT NULL,
    converted_product_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_sourcing_status (status),
    KEY idx_sourcing_created (created_at),
    KEY idx_sourcing_user (user_id),
    KEY idx_sourcing_existing_product (existing_product_id),
    KEY idx_sourcing_converted_product (converted_product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
