SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO categories (name, slug) VALUES ('iPhone', 'iphone') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (name, slug) VALUES ('Android Phones', 'android') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (name, slug) VALUES ('Accessories', 'accessories') ON DUPLICATE KEY UPDATE name=VALUES(name);
INSERT INTO categories (name, slug) VALUES ('Wearables', 'wearables') ON DUPLICATE KEY UPDATE name=VALUES(name);

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='iphone' LIMIT 1), 'Apple iPhone 15 Pro Max', 'apple-iphone-15-pro-max', 'TR-IPH15PM-256', 'Apple', 'Official Warranty', 'smartphone', '256GB Natural Titanium, pro camera system, USB-C, and excellent battery life with Türkiye-ready warranty support.', 'A premium iPhone model for customers who want the strongest Apple camera, performance, and ecosystem experience with official warranty support and fast delivery across Turkey.', '[{"name":"Display","value":"6.7-inch Super Retina XDR"},{"name":"Chip","value":"A17 Pro"},{"name":"Storage","value":"256GB"},{"name":"Camera","value":"48MP Pro camera system"},{"name":"Battery","value":"All-day battery life"},{"name":"Warranty","value":"Official Türkiye warranty"}]', '["Official Türkiye warranty","Installment-friendly checkout","Fast shipping across Turkey","14-day return window"]', 59999.00, 67999.00, 18, 4.90, 'assets/images/apple-iphone-15-pro-max.svg', NULL, 'active', 1, 1) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='apple-iphone-15-pro-max' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='apple-iphone-15-pro-max' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '1TB' FROM products WHERE slug='apple-iphone-15-pro-max' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='1TB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Natural Titanium' FROM products WHERE slug='apple-iphone-15-pro-max' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Natural Titanium');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Blue Titanium' FROM products WHERE slug='apple-iphone-15-pro-max' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Blue Titanium');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Black Titanium' FROM products WHERE slug='apple-iphone-15-pro-max' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Black Titanium');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'Samsung Galaxy S24 Ultra', 'samsung-galaxy-s24-ultra', 'TR-SGS24U-512', 'Samsung', 'Best Seller', 'smartphone', '512GB Titanium Yellow, Galaxy AI features, S Pen, bright AMOLED display, and flagship zoom cameras.', 'Samsung flagship performance with S Pen productivity, strong cameras, and a premium display for users who need a serious Android phone in Turkey.', '[{"name":"Display","value":"6.8-inch Dynamic AMOLED 2X"},{"name":"Chip","value":"Snapdragon 8 Gen 3"},{"name":"Storage","value":"512GB"},{"name":"Camera","value":"200MP main + telephoto zoom"},{"name":"Battery","value":"5000 mAh"},{"name":"Warranty","value":"Official distributor warranty"}]', '["Official distributor warranty","S Pen productivity","Same-day dispatch in selected cities","Secure payment options"]', 42999.00, 48999.00, 22, 4.80, 'assets/images/samsung-galaxy-s24-ultra.svg', NULL, 'active', 1, 1) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='samsung-galaxy-s24-ultra' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='samsung-galaxy-s24-ultra' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '1TB' FROM products WHERE slug='samsung-galaxy-s24-ultra' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='1TB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Titanium Yellow' FROM products WHERE slug='samsung-galaxy-s24-ultra' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Titanium Yellow');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Titanium Gray' FROM products WHERE slug='samsung-galaxy-s24-ultra' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Titanium Gray');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Titanium Black' FROM products WHERE slug='samsung-galaxy-s24-ultra' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Titanium Black');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'Xiaomi 14 5G', 'xiaomi-14-5g', 'TR-XIA14-512', 'Xiaomi', 'Deal', 'smartphone', '512GB storage, Leica-inspired camera experience, fast charging, and compact flagship performance.', 'A fast Android flagship option for customers who want strong performance, a premium camera experience, and excellent value in the Turkish market.', '[{"name":"Display","value":"6.36-inch AMOLED"},{"name":"Chip","value":"Snapdragon 8 Gen 3"},{"name":"Storage","value":"512GB"},{"name":"Camera","value":"Triple 50MP camera system"},{"name":"Charging","value":"Fast wired charging"},{"name":"Connectivity","value":"5G"}]', '["High storage capacity","Fast charging support","Competitive flagship price","Clear warranty status"]', 29999.00, 33499.00, 30, 4.70, 'assets/images/xiaomi-14-5g.svg', NULL, 'active', 1, 1) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='xiaomi-14-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='xiaomi-14-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Black' FROM products WHERE slug='xiaomi-14-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Black');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'White' FROM products WHERE slug='xiaomi-14-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='White');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Jade Green' FROM products WHERE slug='xiaomi-14-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Jade Green');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'Honor 90 5G', 'honor-90-5g', 'TR-HON90-512', 'Honor', 'Free Shipping', 'smartphone', '512GB storage, slim design, bright OLED screen, and balanced camera performance for daily use.', 'A stylish mid-premium Android phone built for shoppers who want storage, display quality, and strong daily performance without flagship pricing.', '[{"name":"Display","value":"6.7-inch OLED"},{"name":"Storage","value":"512GB"},{"name":"Camera","value":"200MP main camera"},{"name":"Battery","value":"5000 mAh"},{"name":"Connectivity","value":"5G"},{"name":"Warranty","value":"Türkiye service support"}]', '["Large internal storage","Free shipping campaign","Good daily battery life","14-day return window"]', 18999.00, 20999.00, 36, 4.60, 'assets/images/honor-90-5g.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='honor-90-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='honor-90-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Emerald Green' FROM products WHERE slug='honor-90-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Emerald Green');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Midnight Black' FROM products WHERE slug='honor-90-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Midnight Black');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Diamond Silver' FROM products WHERE slug='honor-90-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Diamond Silver');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'vivo V30 5G', 'vivo-v30-5g', 'TR-VIVOV30-256', 'vivo', 'New Arrival', 'smartphone', '256GB storage, elegant design, strong selfie camera, and reliable 5G performance.', 'A slim 5G Android phone for customers who care about design, portraits, and reliable everyday performance at a practical price point.', '[{"name":"Display","value":"6.78-inch AMOLED"},{"name":"Storage","value":"256GB"},{"name":"Front Camera","value":"50MP selfie camera"},{"name":"Battery","value":"5000 mAh"},{"name":"Charging","value":"Fast charging"},{"name":"Connectivity","value":"5G"}]', '["Elegant slim body","Strong portrait camera","Free shipping on campaign","Secure checkout"]', 16999.00, 18999.00, 28, 4.50, 'assets/images/vivo-v30-5g.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='vivo-v30-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='vivo-v30-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Aqua Blue' FROM products WHERE slug='vivo-v30-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Aqua Blue');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Noble Black' FROM products WHERE slug='vivo-v30-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Noble Black');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='iphone' LIMIT 1), 'Apple iPhone 15', 'apple-iphone-15', 'TR-IPH15-128', 'Apple', 'Popular', 'smartphone', '128GB, Dynamic Island, 48MP main camera, USB-C, and polished Apple ecosystem experience.', 'A balanced iPhone choice for customers who want the newest Apple essentials, clean performance, and official warranty confidence.', '[{"name":"Display","value":"6.1-inch Super Retina XDR"},{"name":"Chip","value":"A16 Bionic"},{"name":"Storage","value":"128GB"},{"name":"Camera","value":"48MP main camera"},{"name":"Port","value":"USB-C"},{"name":"Warranty","value":"Official Türkiye warranty"}]', '["Official Türkiye warranty","Great resale value","Reliable iOS updates","Installment options"]', 38999.00, 41999.00, 24, 4.90, 'assets/images/apple-iphone-15.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '128GB' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='128GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Black' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Black');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Blue' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Blue');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Pink' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Pink');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Green' FROM products WHERE slug='apple-iphone-15' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Green');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'Samsung Galaxy A55 5G', 'samsung-galaxy-a55-5g', 'TR-SGA55-256', 'Samsung', 'Value Pick', 'smartphone', '256GB, Super AMOLED display, durable body, and balanced Samsung performance for daily use.', 'A practical Samsung model for customers who want a durable Android phone, good camera quality, and brand reliability at a fair price.', '[{"name":"Display","value":"6.6-inch Super AMOLED"},{"name":"Storage","value":"256GB"},{"name":"Camera","value":"50MP main camera"},{"name":"Battery","value":"5000 mAh"},{"name":"Build","value":"Metal frame"},{"name":"Connectivity","value":"5G"}]', '["Strong value segment","Samsung service network","Free shipping campaign","Long-term software support"]', 15999.00, 17999.00, 42, 4.70, 'assets/images/samsung-galaxy-a55-5g.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '128GB' FROM products WHERE slug='samsung-galaxy-a55-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='128GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='samsung-galaxy-a55-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Awesome Navy' FROM products WHERE slug='samsung-galaxy-a55-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Awesome Navy');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Awesome Iceblue' FROM products WHERE slug='samsung-galaxy-a55-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Awesome Iceblue');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Awesome Lilac' FROM products WHERE slug='samsung-galaxy-a55-5g' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Awesome Lilac');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'Xiaomi Redmi Note 13 Pro+', 'xiaomi-redmi-note-13-pro-plus', 'TR-RN13P-512', 'Xiaomi', 'Top Rated', 'smartphone', '512GB storage, curved AMOLED display, 200MP camera, and fast charging at a strong price.', 'A powerful value phone for shoppers who want large storage, a sharp display, and fast charging without jumping into flagship pricing.', '[{"name":"Display","value":"6.67-inch AMOLED"},{"name":"Storage","value":"512GB"},{"name":"Camera","value":"200MP main camera"},{"name":"Charging","value":"Fast wired charging"},{"name":"Battery","value":"5000 mAh"},{"name":"Connectivity","value":"5G"}]', '["512GB storage option","Very fast charging","Strong camera value","Competitive Türkiye pricing"]', 13999.00, 15999.00, 45, 4.60, 'assets/images/xiaomi-redmi-note-13-pro-plus.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='xiaomi-redmi-note-13-pro-plus' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '512GB' FROM products WHERE slug='xiaomi-redmi-note-13-pro-plus' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='512GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Midnight Black' FROM products WHERE slug='xiaomi-redmi-note-13-pro-plus' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Midnight Black');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Moonlight White' FROM products WHERE slug='xiaomi-redmi-note-13-pro-plus' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Moonlight White');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Aurora Purple' FROM products WHERE slug='xiaomi-redmi-note-13-pro-plus' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Aurora Purple');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='android' LIMIT 1), 'Samsung Galaxy S23 FE', 'samsung-galaxy-s23-fe', 'TR-SGS23FE-256', 'Samsung', 'Outlet Deal', 'smartphone', '256GB, flagship-inspired camera, AMOLED screen, and reliable Samsung performance at a lower price.', 'A strong Samsung option for shoppers who want flagship-like features while keeping the total basket more reasonable.', '[{"name":"Display","value":"6.4-inch Dynamic AMOLED 2X"},{"name":"Storage","value":"256GB"},{"name":"Camera","value":"50MP main camera"},{"name":"Battery","value":"4500 mAh"},{"name":"Connectivity","value":"5G"},{"name":"Warranty","value":"Official service support"}]', '["Outlet-style value","Samsung warranty support","Good camera system","Secure payment"]', 18499.00, 21499.00, 20, 4.60, 'assets/images/samsung-galaxy-s23-fe.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '128GB' FROM products WHERE slug='samsung-galaxy-s23-fe' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='128GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'storage', '256GB' FROM products WHERE slug='samsung-galaxy-s23-fe' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='storage' AND option_value='256GB');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Graphite' FROM products WHERE slug='samsung-galaxy-s23-fe' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Graphite');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Mint' FROM products WHERE slug='samsung-galaxy-s23-fe' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Mint');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Cream' FROM products WHERE slug='samsung-galaxy-s23-fe' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Cream');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='accessories' LIMIT 1), 'Apple AirPods Pro USB-C', 'apple-airpods-pro-usb-c', 'TR-APP-USB-C', 'Apple', 'Accessory', 'accessory', 'Wireless earbuds with active noise cancellation, transparency mode, and USB-C charging case.', 'Premium earbuds for iPhone users who want clean pairing, strong noise cancellation, and reliable all-day listening.', '[{"name":"Type","value":"Wireless earbuds"},{"name":"Charging","value":"USB-C case"},{"name":"Noise Control","value":"Active noise cancellation"},{"name":"Compatibility","value":"iPhone and Bluetooth devices"}]', '["Active noise cancellation","USB-C charging case","Great iPhone pairing","Compact daily carry"]', 8499.00, 9499.00, 32, 4.80, 'assets/images/apple-airpods-pro-usb-c.svg', NULL, 'active', 1, 1) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'White' FROM products WHERE slug='apple-airpods-pro-usb-c' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='White');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='accessories' LIMIT 1), 'Samsung 25W USB-C Charger', 'samsung-25w-usb-c-charger', 'TR-SAM-25W-USB-C', 'Samsung', 'Fast Charge', 'accessory', 'Compact 25W USB-C wall charger for compatible Samsung and Android devices.', 'A reliable charger accessory for customers who want safe, compact fast charging for daily phone use.', '[{"name":"Power","value":"25W"},{"name":"Port","value":"USB-C"},{"name":"Compatibility","value":"Samsung and USB-C devices"},{"name":"Warranty","value":"Seller warranty"}]', '["Compact wall charger","USB-C output","Fast charging support","Good accessory margin"]', 799.00, 999.00, 75, 4.70, 'assets/images/samsung-25w-usb-c-charger.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'White' FROM products WHERE slug='samsung-25w-usb-c-charger' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='White');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Black' FROM products WHERE slug='samsung-25w-usb-c-charger' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Black');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='accessories' LIMIT 1), 'MagSafe Compatible Clear Case', 'magsafe-compatible-clear-case', 'TR-MAG-CASE-15', 'Phonix', 'Case', 'accessory', 'Clear protective case with magnetic alignment for iPhone 15 series.', 'A clean protective case for iPhone users who want visible color, magnetic accessory support, and daily scratch protection.', '[{"name":"Material","value":"Clear TPU + polycarbonate"},{"name":"Compatibility","value":"iPhone 15 series"},{"name":"Magnetic","value":"MagSafe compatible"},{"name":"Protection","value":"Raised camera lip"}]', '["Magnetic alignment","Slim protection","Clear finish","Easy upsell with iPhone"]', 1199.00, 1499.00, 60, 4.50, 'assets/images/magsafe-compatible-clear-case.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Clear' FROM products WHERE slug='magsafe-compatible-clear-case' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Clear');

INSERT INTO products (category_id, name, slug, sku, brand, badge, product_type, short_description, description, specs_json, benefits_json, price, compare_price, stock, rating, image, gallery_json, product_status, is_active, is_featured) VALUES ((SELECT id FROM categories WHERE slug='wearables' LIMIT 1), 'Galaxy Watch 6 Classic', 'galaxy-watch-6-classic', 'TR-GW6C-43', 'Samsung', 'Wearable', 'wearable', 'Classic smartwatch with health tracking, premium build, and Android phone integration.', 'A smartwatch option for Android customers who want fitness tracking, notifications, and a premium wrist experience.', '[{"name":"Size","value":"43mm"},{"name":"Connectivity","value":"Bluetooth"},{"name":"Health","value":"Heart rate and sleep tracking"},{"name":"Compatibility","value":"Android phones"}]', '["Health tracking","Android integration","Premium classic design","Good bundle with phones"]', 7499.00, 8499.00, 19, 4.70, 'assets/images/galaxy-watch-6-classic.svg', NULL, 'active', 1, 0) ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), name=VALUES(name), sku=VALUES(sku), brand=VALUES(brand), badge=VALUES(badge), product_type=VALUES(product_type), short_description=VALUES(short_description), description=VALUES(description), specs_json=VALUES(specs_json), benefits_json=VALUES(benefits_json), price=VALUES(price), compare_price=VALUES(compare_price), stock=VALUES(stock), rating=VALUES(rating), image=VALUES(image), product_status=VALUES(product_status), is_active=VALUES(is_active), is_featured=VALUES(is_featured);
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Black' FROM products WHERE slug='galaxy-watch-6-classic' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Black');
INSERT INTO product_variants (product_id, option_type, option_value) SELECT id, 'color', 'Silver' FROM products WHERE slug='galaxy-watch-6-classic' AND NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id=products.id AND option_type='color' AND option_value='Silver');

INSERT INTO site_settings (setting_key, setting_value) VALUES ('site_name', 'Phonix Türkiye'), ('site_currency', 'TRY'), ('support_email', 'support@phonixturkiye.com'), ('support_phone', '0850 305 20 20'), ('support_chat_label', 'Weekdays 09:00 - 18:00 (TRT)'), ('footer_tagline', 'Official phones, trusted warranty, fast delivery across Turkey.'), ('announcement_text', ''), ('shipping_info_text', 'Shipping and payment choices are saved directly into each phone order.'), ('email_from_name', 'Phonix Türkiye'), ('email_from_email', 'no-reply@phonixturkiye.com'), ('email_admin_alert_email', 'support@phonixturkiye.com'), ('site_meta_title', 'Phonix Türkiye | Phones, iPhone, Android & Accessories'), ('site_meta_description', 'A Turkey-focused smartphone marketplace for iPhone, Samsung, Xiaomi, Honor, vivo, accessories, warranty-backed shopping, and fast delivery.'), ('homepage_eyebrow', 'TURKEY SMARTPHONE MARKETPLACE'), ('homepage_title_line_1', 'Phones for Turkey.'), ('homepage_title_line_2', 'Ready to ship.'), ('homepage_subtitle', 'Shop iPhone, Samsung, Xiaomi, Honor, vivo, and essential accessories with clear warranty status, secure checkout, installment-friendly prices, and fast delivery across Turkey.'), ('homepage_primary_cta_label', 'Shop Phones'), ('homepage_primary_cta_url', 'products.php'), ('homepage_secondary_cta_label', 'View Deals'), ('homepage_secondary_cta_url', 'deals.php'), ('homepage_trust_text', 'Trusted by phone buyers across Turkey'), ('homepage_hero_image', 'assets/images/samsung-galaxy-s24-ultra.svg') ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);

INSERT INTO site_pages (page_key, page_label, meta_title, meta_description, robots_index, is_active) VALUES ('home','Home','Phonix Türkiye | Phones, iPhone, Android & Accessories','Shop original smartphones and accessories in Turkey with secure checkout, clear warranty support, and fast delivery.',1,1) ON DUPLICATE KEY UPDATE page_label=VALUES(page_label), meta_title=VALUES(meta_title), meta_description=VALUES(meta_description), robots_index=VALUES(robots_index), is_active=VALUES(is_active);
INSERT INTO site_pages (page_key, page_label, meta_title, meta_description, robots_index, is_active) VALUES ('products','Products','Phones & Accessories | Phonix Türkiye','Browse iPhone, Android phones, wearables, and phone accessories available for Turkey.',1,1) ON DUPLICATE KEY UPDATE page_label=VALUES(page_label), meta_title=VALUES(meta_title), meta_description=VALUES(meta_description), robots_index=VALUES(robots_index), is_active=VALUES(is_active);
INSERT INTO site_pages (page_key, page_label, meta_title, meta_description, robots_index, is_active) VALUES ('deals','Deals','Phone Deals in Turkey | Phonix Türkiye','Limited-time smartphone and accessory offers with warranty-backed shopping.',1,1) ON DUPLICATE KEY UPDATE page_label=VALUES(page_label), meta_title=VALUES(meta_title), meta_description=VALUES(meta_description), robots_index=VALUES(robots_index), is_active=VALUES(is_active);
INSERT INTO site_pages (page_key, page_label, meta_title, meta_description, robots_index, is_active) VALUES ('support','Support','Phone Order Support | Phonix Türkiye','Get help with phone orders, delivery, warranty, returns, and payment questions.',1,1) ON DUPLICATE KEY UPDATE page_label=VALUES(page_label), meta_title=VALUES(meta_title), meta_description=VALUES(meta_description), robots_index=VALUES(robots_index), is_active=VALUES(is_active);

INSERT INTO homepage_featured_slots (slot_key, product_id, title_override, subtitle_override, badge_override, sort_order, is_active) SELECT 'hero', id, 'Samsung Galaxy S24 Ultra', 'Galaxy AI, S Pen, 512GB storage, and official warranty confidence for Turkey.', 'Flagship', 1, 1 FROM products WHERE slug='samsung-galaxy-s24-ultra' ON DUPLICATE KEY UPDATE product_id=VALUES(product_id), title_override=VALUES(title_override), subtitle_override=VALUES(subtitle_override), badge_override=VALUES(badge_override), sort_order=VALUES(sort_order), is_active=VALUES(is_active);
INSERT INTO homepage_featured_slots (slot_key, product_id, title_override, subtitle_override, badge_override, sort_order, is_active) SELECT 'audio', id, 'AirPods Pro USB-C', 'Noise cancellation and seamless iPhone pairing for daily commuting.', 'Accessory', 2, 1 FROM products WHERE slug='apple-airpods-pro-usb-c' ON DUPLICATE KEY UPDATE product_id=VALUES(product_id), title_override=VALUES(title_override), subtitle_override=VALUES(subtitle_override), badge_override=VALUES(badge_override), sort_order=VALUES(sort_order), is_active=VALUES(is_active);
INSERT INTO homepage_featured_slots (slot_key, product_id, title_override, subtitle_override, badge_override, sort_order, is_active) SELECT 'watch', id, 'Apple iPhone 15', 'The balanced iPhone choice with USB-C, Dynamic Island, and official warranty.', 'Popular', 3, 1 FROM products WHERE slug='apple-iphone-15' ON DUPLICATE KEY UPDATE product_id=VALUES(product_id), title_override=VALUES(title_override), subtitle_override=VALUES(subtitle_override), badge_override=VALUES(badge_override), sort_order=VALUES(sort_order), is_active=VALUES(is_active);

DELETE FROM homepage_banners WHERE title IN ('Trade in your old phone','Student-ready phone bundles');
DELETE FROM support_faqs WHERE question IN ('How long does phone delivery take in Turkey?','Are the phones covered by warranty?','Can customers pay by card or installment?','Can a phone be returned?');

INSERT INTO homepage_banners (title, subtitle, eyebrow, cta_label, cta_url, image_path, sort_order, is_active) VALUES ('Trade in your old phone','Get a better phone with a smarter upgrade path. Ask support about device assessment before checkout.','Upgrade Program','Start Assessment','support.php','assets/images/apple-iphone-15.svg',1,1);
INSERT INTO homepage_banners (title, subtitle, eyebrow, cta_label, cta_url, image_path, sort_order, is_active) VALUES ('Student-ready phone bundles','Phones, chargers, cases, and earbuds prepared for daily university life in Turkey.','Bundle Deals','Shop Accessories','products.php?category=accessories','assets/images/apple-airpods-pro-usb-c.svg',2,1);

INSERT INTO support_faqs (question, answer, category, sort_order, is_active) VALUES ('How long does phone delivery take in Turkey?','In-stock phone orders are usually prepared within 1 business day. Delivery timing depends on the city and selected shipping method.','Shipping',1,1);
INSERT INTO support_faqs (question, answer, category, sort_order, is_active) VALUES ('Are the phones covered by warranty?','Each product page should clearly show its warranty status. Prefer official distributor warranty items when you need full local service confidence.','Warranty',2,1);
INSERT INTO support_faqs (question, answer, category, sort_order, is_active) VALUES ('Can customers pay by card or installment?','The checkout flow supports the active payment methods configured in the admin panel. Use the product and payment settings to communicate installment options clearly.','Payments',3,1);
INSERT INTO support_faqs (question, answer, category, sort_order, is_active) VALUES ('Can a phone be returned?','Returns depend on the return policy and product condition. Keep the original box, accessories, and invoice for any return or service request.','Returns',4,1);

SET FOREIGN_KEY_CHECKS = 1;
